[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "shifthtml"
version = "0.2.0"
description = "A concise HTML renderer."
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["anyio>=4.0"]

[dependency-groups]
dev = [
    "ty>=0.0.1a7",
    "ruff",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
]

[tool.ty.src]
include = ["src/", "tests/"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
