[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shifthtml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "ruff",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
