from .node import HTMLElement, HTMLVoidElement, Tag

# Root
html = Tag[HTMLElement]("html")
head = Tag[HTMLElement]("head")
body = Tag[HTMLElement]("body")

# Metadata
base = Tag[HTMLVoidElement]("base", void=True)
link = Tag[HTMLVoidElement]("link", void=True)
meta = Tag[HTMLVoidElement]("meta", void=True)
style = Tag[HTMLElement]("style")
title = Tag[HTMLElement]("title")

# Sectioning
address = Tag[HTMLElement]("address")
article = Tag[HTMLElement]("article")
aside = Tag[HTMLElement]("aside")
footer = Tag[HTMLElement]("footer")
header = Tag[HTMLElement]("header")
h1 = Tag[HTMLElement]("h1")
h2 = Tag[HTMLElement]("h2")
h3 = Tag[HTMLElement]("h3")
h4 = Tag[HTMLElement]("h4")
h5 = Tag[HTMLElement]("h5")
h6 = Tag[HTMLElement]("h6")
main = Tag[HTMLElement]("main")
nav = Tag[HTMLElement]("nav")
section = Tag[HTMLElement]("section")

# Grouping content
blockquote = Tag[HTMLElement]("blockquote")
dd = Tag[HTMLElement]("dd")
div = Tag[HTMLElement]("div")
dl = Tag[HTMLElement]("dl")
dt = Tag[HTMLElement]("dt")
figcaption = Tag[HTMLElement]("figcaption")
figure = Tag[HTMLElement]("figure")
hr = Tag[HTMLVoidElement]("hr", void=True)
li = Tag[HTMLElement]("li")
ol = Tag[HTMLElement]("ol")
p = Tag[HTMLElement]("p")
pre = Tag[HTMLElement]("pre")
ul = Tag[HTMLElement]("ul")

# Text-level semantics
a = Tag[HTMLElement]("a")
abbr = Tag[HTMLElement]("abbr")
b = Tag[HTMLElement]("b")
bdi = Tag[HTMLElement]("bdi")
bdo = Tag[HTMLElement]("bdo")
br = Tag[HTMLVoidElement]("br", void=True)
cite = Tag[HTMLElement]("cite")
code = Tag[HTMLElement]("code")
data = Tag[HTMLElement]("data")
dfn = Tag[HTMLElement]("dfn")
em = Tag[HTMLElement]("em")
i = Tag[HTMLElement]("i")
kbd = Tag[HTMLElement]("kbd")
mark = Tag[HTMLElement]("mark")
q = Tag[HTMLElement]("q")
rp = Tag[HTMLElement]("rp")
rt = Tag[HTMLElement]("rt")
ruby = Tag[HTMLElement]("ruby")
s = Tag[HTMLElement]("s")
samp = Tag[HTMLElement]("samp")
small = Tag[HTMLElement]("small")
span = Tag[HTMLElement]("span")
strong = Tag[HTMLElement]("strong")
sub = Tag[HTMLElement]("sub")
sup = Tag[HTMLElement]("sup")
time = Tag[HTMLElement]("time")
u = Tag[HTMLElement]("u")
var = Tag[HTMLElement]("var")
wbr = Tag[HTMLVoidElement]("wbr", void=True)

# Edits
del_ = Tag[HTMLElement]("del")
ins = Tag[HTMLElement]("ins")

# Embedded content
area = Tag[HTMLVoidElement]("area", void=True)
audio = Tag[HTMLElement]("audio")
img = Tag[HTMLVoidElement]("img", void=True)
map_ = Tag[HTMLElement]("map")
track = Tag[HTMLVoidElement]("track", void=True)
video = Tag[HTMLElement]("video")
embed = Tag[HTMLVoidElement]("embed", void=True)
iframe = Tag[HTMLElement]("iframe")
object_ = Tag[HTMLElement]("object")
picture = Tag[HTMLElement]("picture")
portal = Tag[HTMLElement]("portal")
source = Tag[HTMLVoidElement]("source", void=True)

# Scripting
canvas = Tag[HTMLElement]("canvas")
noscript = Tag[HTMLElement]("noscript")
script = Tag[HTMLElement]("script")

# Demarcating edits
del_ = Tag[HTMLElement]("del")
ins = Tag[HTMLElement]("ins")

# Table content
caption = Tag[HTMLElement]("caption")
col = Tag[HTMLVoidElement]("col", void=True)
colgroup = Tag[HTMLElement]("colgroup")
table = Tag[HTMLElement]("table")
tbody = Tag[HTMLElement]("tbody")
td = Tag[HTMLElement]("td")
tfoot = Tag[HTMLElement]("tfoot")
th = Tag[HTMLElement]("th")
thead = Tag[HTMLElement]("thead")
tr = Tag[HTMLElement]("tr")

# Forms
button = Tag[HTMLElement]("button")
datalist = Tag[HTMLElement]("datalist")
fieldset = Tag[HTMLElement]("fieldset")
form = Tag[HTMLElement]("form")
input_ = Tag[HTMLVoidElement]("input", void=True)
label = Tag[HTMLElement]("label")
legend = Tag[HTMLElement]("legend")
meter = Tag[HTMLElement]("meter")
optgroup = Tag[HTMLElement]("optgroup")
option = Tag[HTMLElement]("option")
output = Tag[HTMLElement]("output")
progress = Tag[HTMLElement]("progress")
select = Tag[HTMLElement]("select")
textarea = Tag[HTMLElement]("textarea")

# Interactive elements
details = Tag[HTMLElement]("details")
dialog = Tag[HTMLElement]("dialog")
menu = Tag[HTMLElement]("menu")
summary = Tag[HTMLElement]("summary")

# Web Components
slot = Tag[HTMLElement]("slot")
template = Tag[HTMLElement]("template")
