from .node import Element, VoidElement, Tag

# Root
html = Tag[Element]("html", Element)
head = Tag[Element]("head", Element)
body = Tag[Element]("body", Element)

# Metadata
base = Tag[VoidElement]("base", VoidElement)
link = Tag[VoidElement]("link", VoidElement)
meta = Tag[VoidElement]("meta", VoidElement)
style = Tag[Element]("style", Element)
title = Tag[Element]("title", Element)

# Sectioning
address = Tag[Element]("address", Element)
article = Tag[Element]("article", Element)
aside = Tag[Element]("aside", Element)
footer = Tag[Element]("footer", Element)
header = Tag[Element]("header", Element)
h1 = Tag[Element]("h1", Element)
h2 = Tag[Element]("h2", Element)
h3 = Tag[Element]("h3", Element)
h4 = Tag[Element]("h4", Element)
h5 = Tag[Element]("h5", Element)
h6 = Tag[Element]("h6", Element)
main = Tag[Element]("main", Element)
nav = Tag[Element]("nav", Element)
section = Tag[Element]("section", Element)

# Grouping content
blockquote = Tag[Element]("blockquote", Element)
dd = Tag[Element]("dd", Element)
div = Tag[Element]("div", Element)
dl = Tag[Element]("dl", Element)
dt = Tag[Element]("dt", Element)
figcaption = Tag[Element]("figcaption", Element)
figure = Tag[Element]("figure", Element)
hr = Tag[VoidElement]("hr", VoidElement)
li = Tag[Element]("li", Element)
ol = Tag[Element]("ol", Element)
p = Tag[Element]("p", Element)
pre = Tag[Element]("pre", Element)
ul = Tag[Element]("ul", Element)

# Text-level semantics
a = Tag[Element]("a", Element)
abbr = Tag[Element]("abbr", Element)
b = Tag[Element]("b", Element)
bdi = Tag[Element]("bdi", Element)
bdo = Tag[Element]("bdo", Element)
br = Tag[VoidElement]("br", VoidElement)
cite = Tag[Element]("cite", Element)
code = Tag[Element]("code", Element)
data = Tag[Element]("data", Element)
dfn = Tag[Element]("dfn", Element)
em = Tag[Element]("em", Element)
i = Tag[Element]("i", Element)
kbd = Tag[Element]("kbd", Element)
mark = Tag[Element]("mark", Element)
q = Tag[Element]("q", Element)
rp = Tag[Element]("rp", Element)
rt = Tag[Element]("rt", Element)
ruby = Tag[Element]("ruby", Element)
s = Tag[Element]("s", Element)
samp = Tag[Element]("samp", Element)
small = Tag[Element]("small", Element)
span = Tag[Element]("span", Element)
strong = Tag[Element]("strong", Element)
sub = Tag[Element]("sub", Element)
sup = Tag[Element]("sup", Element)
time = Tag[Element]("time", Element)
u = Tag[Element]("u", Element)
var = Tag[Element]("var", Element)
wbr = Tag[VoidElement]("wbr", VoidElement)

# Edits
del_ = Tag[Element]("del", Element)
ins = Tag[Element]("ins", Element)

# Embedded content
area = Tag[VoidElement]("area", VoidElement)
audio = Tag[Element]("audio", Element)
img = Tag[VoidElement]("img", VoidElement)
map_ = Tag[Element]("map", Element)
track = Tag[VoidElement]("track", VoidElement)
video = Tag[Element]("video", Element)
embed = Tag[VoidElement]("embed", VoidElement)
iframe = Tag[Element]("iframe", Element)
object_ = Tag[Element]("object", Element)
picture = Tag[Element]("picture", Element)
portal = Tag[Element]("portal", Element)
source = Tag[VoidElement]("source", VoidElement)

# Scripting
canvas = Tag[Element]("canvas", Element)
noscript = Tag[Element]("noscript", Element)
script = Tag[Element]("script", Element)

# Demarcating edits
del_ = Tag[Element]("del", Element)
ins = Tag[Element]("ins", Element)

# Table content
caption = Tag[Element]("caption", Element)
col = Tag[VoidElement]("col", VoidElement)
colgroup = Tag[Element]("colgroup", Element)
table = Tag[Element]("table", Element)
tbody = Tag[Element]("tbody", Element)
td = Tag[Element]("td", Element)
tfoot = Tag[Element]("tfoot", Element)
th = Tag[Element]("th", Element)
thead = Tag[Element]("thead", Element)
tr = Tag[Element]("tr", Element)

# Forms
button = Tag[Element]("button", Element)
datalist = Tag[Element]("datalist", Element)
fieldset = Tag[Element]("fieldset", Element)
form = Tag[Element]("form", Element)
input_ = Tag[VoidElement]("input", VoidElement)
label = Tag[Element]("label", Element)
legend = Tag[Element]("legend", Element)
meter = Tag[Element]("meter", Element)
optgroup = Tag[Element]("optgroup", Element)
option = Tag[Element]("option", Element)
output = Tag[Element]("output", Element)
progress = Tag[Element]("progress", Element)
select = Tag[Element]("select", Element)
textarea = Tag[Element]("textarea", Element)

# Interactive elements
details = Tag[Element]("details", Element)
dialog = Tag[Element]("dialog", Element)
menu = Tag[Element]("menu", Element)
summary = Tag[Element]("summary", Element)

# Web Components
slot = Tag[Element]("slot", Element)
template = Tag[Element]("template", Element)
